<#
    .SYNOPSIS


    .DESCRIPTION
    We will use this to build qualifiers that are syntactically correct and properly escaped.

    .NOTES
    Snippet from the API docs:

        Qualifier clauses are in the following format:
        (<attribute> <op> <value>)
        where:
        - <attribute> is the attribute name.
        - <op> is one of the following operations: =, !=, <, >, <=, >=, like, or caseInsensitiveLike.
        When like or caseInsensitiveLike is used, <value> may contain asterisks (*) as wildcard
        placeholders.
        - <value> is the attribute value. It could be a number, string, date, and so on. String and date
        values must be enclosed with single quotes (for example, 'some string value').
        Qualifier clauses can be joined and nested with the keywords and, or, and not. Additionally, left and
        right brackets - '(' and ')' - can be used to create more complex qualifiers.
        To reference nested attributes, use a period to join the components of the attribute path (for example,
        location.locationName).
        When providing the qualifier as a GET query parameter, remember to percent-encode it:
        https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters

    FIXME: This is a w.i.p.
#>
function Join-WHDQualifier {
    [CmdletBinding()]
    [OutputType([string])]
    param (
        [Parameter(Mandatory)]
        [string[]] $Qualifiers,

        [Parameter(Mandatory)]
        [ValidateSet("and", "or")] # FIXME: We need to support "not"
        [string] $JoinOperator
    )

    # FIXME: Should we add an enum for the join operator?
    # FIXME: Should we validate qualifiers as having been generated by New-WHDQualifier or something?
    return "($($Qualifiers -join " $JoinOperator "))"
}