<#
    .SYNOPSIS
    Join multiple WHD API qualifiers together with a logical operator.

    .DESCRIPTION
    This function joins multiple WHD API qualifiers together using a specified logical operator.

    .PARAMETER Qualifiers
    An array of qualifiers to join together. These should be generated by the New-WHDQualifier function.

    .PARAMETER JoinOperator
    The logical operator to use when joining the qualifiers.
    Options are AND and OR.

    .EXAMPLE
    $Qualifier1 = New-WHDQualifier -Attribute "email" -Operator "Equals" -Value "user@example.com"
    $Qualifier2 = New-WHDQualifier -Attribute "department" -Operator "Equals" -Value "IT"
    $JoinedQualifier = Join-WHDQualifier -Qualifiers @($Qualifier1, $Qualifier2) -JoinOperator "AND"
#>
function Join-WHDQualifier {
    [CmdletBinding()]
    [OutputType([string])]
    param (
        [Parameter(Mandatory, Position = 0)]
        [string[]] $Qualifiers,

        [Parameter(Mandatory, Position = 1)]
        [WHDQualifierLogicalOperator] $JoinOperator
    )

    # If we only have one qualifier, just return it without the operator
    # This avoids unneccessary extra parentheses in the common case of a single qualifier
    if ($Qualifiers.Count -eq 1) { return $Qualifiers[0] }

    # FIXME: Should we validate qualifiers as having been generated by New-WHDQualifier or something?
    return "($($Qualifiers -join " $JoinOperator "))"
}